---
- hosts: 172.31.20.22
  become: yes
  tasks:
  - name: i want to execute direct linux command
    command: hostname -f
    register: myfirsttaskresult




  - name: i want to disply first tasks result
    debug:
      msg: "{{myfirsttaskresult}}"