---
- name: copy tomcat user xml file into node sides
  template:
        src: templates/mytomuser.j2
        dest: /opt/tomcat/conf/tomcat-users.xml


- name: copy tomcat context file into nodes sides
  template: 
          src: templates/mytomcontext.j2
          dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy tomcat host context file into node sides
  template:
         src: templates/myhostcontext.j2
         dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml